project:
  type: book
  output-dir: _book

book:
  title: "OpenIntro Applied Statistics"
  author: "Noman"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

execute:
  echo: false
  warning: false
  fig-format: png

format:
  pdf:
    documentclass: scrbook
    papersize: letter
    fontsize: 10pt
    linestretch: 1.15
    callout-appearance: default
    callout-icon: true
    include-in-header: latex/openintro.tex
    pdf-engine: xelatex
    toc: true
    number-sections: true
  epub:
    toc: true
    number-sections: true